-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.information_address
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    line1 character varying(50) COLLATE pg_catalog."default" NOT NULL,
    line2 character varying(30) COLLATE pg_catalog."default",
    city_id integer,
    CONSTRAINT information_address_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_city
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "City_name" character varying(30) COLLATE pg_catalog."default",
    governorate_id integer,
    CONSTRAINT information_city_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_courseenrollment
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "TA_ID_id" integer NOT NULL,
    "professor_ID_id" integer NOT NULL,
    "student_ID_id" integer NOT NULL,
    "subject_ID_id" integer NOT NULL,
    CONSTRAINT information_courseenrollment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_department
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT information_department_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_employee
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(200) COLLATE pg_catalog."default" NOT NULL,
    image character varying(100) COLLATE pg_catalog."default",
    ssn character varying(15) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(14) COLLATE pg_catalog."default",
    salary numeric(10, 5) NOT NULL,
    birth_date date,
    password character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "Address_id" integer,
    "jobDescription" text COLLATE pg_catalog."default" NOT NULL,
    speciality character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT information_employee_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_exam
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    hall character varying(50) COLLATE pg_catalog."default" NOT NULL,
    from_time timestamp with time zone,
    "to" timestamp with time zone,
    subject_id integer NOT NULL,
    CONSTRAINT information_exam_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_governorate
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Governorate_Name" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "zipCode" integer NOT NULL,
    CONSTRAINT information_governorate_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_professor
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(200) COLLATE pg_catalog."default" NOT NULL,
    image character varying(100) COLLATE pg_catalog."default",
    ssn character varying(15) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(14) COLLATE pg_catalog."default" NOT NULL,
    salary numeric(7, 5) NOT NULL,
    birth_date date,
    password character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "Address_id" integer,
    department_id integer NOT NULL,
    subject_id integer NOT NULL,
    CONSTRAINT information_professor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_professordepartment
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "Department_ID_id" integer NOT NULL,
    "professor_ID_id" integer NOT NULL,
    CONSTRAINT information_professordepartment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_professorsubject
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "TA_ID_id" integer NOT NULL,
    "professor_ID_id" integer NOT NULL,
    "subject_ID_id" integer NOT NULL,
    CONSTRAINT information_professorsubject_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_section
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT information_section_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_student
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(200) COLLATE pg_catalog."default" NOT NULL,
    image character varying(100) COLLATE pg_catalog."default",
    ssn character varying(15) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(14) COLLATE pg_catalog."default" NOT NULL,
    birth_date date,
    password character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "Address_id" integer,
    department_id integer NOT NULL,
    subject_id integer NOT NULL,
    year integer NOT NULL,
    CONSTRAINT information_student_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_student_ta
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TA_ID_id" integer NOT NULL,
    "student_ID_id" integer NOT NULL,
    "subject_ID_id" integer NOT NULL,
    CONSTRAINT information_student_ta_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_studentprofessor
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "professor_ID_id" integer NOT NULL,
    "student_ID_id" integer NOT NULL,
    "subject_ID_id" integer NOT NULL,
    CONSTRAINT information_studentprofessor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_studentsection
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "section_ID_id" integer NOT NULL,
    "student_ID_id" integer NOT NULL,
    CONSTRAINT information_studentsection_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_studentsubject
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "TA_ID_id" integer NOT NULL,
    "professor_ID_id" integer NOT NULL,
    "student_ID_id" integer NOT NULL,
    "subject_ID_id" integer NOT NULL,
    CONSTRAINT information_studentsubject_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_subject
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT information_subject_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_ta_department
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "Department_ID_id" integer NOT NULL,
    "TA_ID_id" integer NOT NULL,
    CONSTRAINT information_ta_department_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_ta_section
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "TA_ID_id" integer NOT NULL,
    "section_ID_id" integer NOT NULL,
    CONSTRAINT information_ta_section_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_ta_subject
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "TA_ID_id" integer NOT NULL,
    "professor_ID_id" integer NOT NULL,
    "subject_ID_id" integer NOT NULL,
    CONSTRAINT information_ta_subject_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.information_teachingassistant
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(200) COLLATE pg_catalog."default" NOT NULL,
    image character varying(100) COLLATE pg_catalog."default",
    ssn character varying(15) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(14) COLLATE pg_catalog."default" NOT NULL,
    salary numeric(7, 5) NOT NULL,
    birth_date date,
    password character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "Address_id" integer,
    department_id integer NOT NULL,
    subject_id integer NOT NULL,
    CONSTRAINT information_teachingassistant_pkey PRIMARY KEY (id),
    CONSTRAINT information_teachingassistant_department_id_56c3cb4c_uniq UNIQUE (department_id),
    CONSTRAINT information_teachingassistant_subject_id_0e27c5f3_uniq UNIQUE (subject_id)
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.information_address
    ADD CONSTRAINT information_address_city_id_e301f5d0_fk_information_city_id FOREIGN KEY (city_id)
    REFERENCES public.information_city (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS information_address_city_id_e301f5d0
    ON public.information_address(city_id);


ALTER TABLE IF EXISTS public.information_city
    ADD CONSTRAINT information_city_governorate_id_d7892769_fk_informati FOREIGN KEY (governorate_id)
    REFERENCES public.information_governorate (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS information_city_governorate_id_d7892769
    ON public.information_city(governorate_id);


ALTER TABLE IF EXISTS public.information_courseenrollment
    ADD CONSTRAINT "information_courseen_TA_ID_id_2f7e6179_fk_informati" FOREIGN KEY ("TA_ID_id")
    REFERENCES public.information_teachingassistant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_courseenrollment_TA_ID_id_2f7e6179"
    ON public.information_courseenrollment("TA_ID_id");


ALTER TABLE IF EXISTS public.information_courseenrollment
    ADD CONSTRAINT "information_courseen_professor_ID_id_46b0914a_fk_informati" FOREIGN KEY ("professor_ID_id")
    REFERENCES public.information_professor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_courseenrollment_professor_ID_id_46b0914a"
    ON public.information_courseenrollment("professor_ID_id");


ALTER TABLE IF EXISTS public.information_courseenrollment
    ADD CONSTRAINT "information_courseen_student_ID_id_8be1ecd3_fk_informati" FOREIGN KEY ("student_ID_id")
    REFERENCES public.information_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_courseenrollment_student_ID_id_8be1ecd3"
    ON public.information_courseenrollment("student_ID_id");


ALTER TABLE IF EXISTS public.information_courseenrollment
    ADD CONSTRAINT "information_courseen_subject_ID_id_b99ea307_fk_informati" FOREIGN KEY ("subject_ID_id")
    REFERENCES public.information_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_courseenrollment_subject_ID_id_b99ea307"
    ON public.information_courseenrollment("subject_ID_id");


ALTER TABLE IF EXISTS public.information_employee
    ADD CONSTRAINT "information_employee_Address_id_b0ef462e_fk_informati" FOREIGN KEY ("Address_id")
    REFERENCES public.information_address (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_employee_Address_id_b0ef462e"
    ON public.information_employee("Address_id");


ALTER TABLE IF EXISTS public.information_exam
    ADD CONSTRAINT information_exam_subject_id_7e6750e2_fk_information_subject_id FOREIGN KEY (subject_id)
    REFERENCES public.information_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS information_exam_subject_id_7e6750e2
    ON public.information_exam(subject_id);


ALTER TABLE IF EXISTS public.information_professor
    ADD CONSTRAINT "information_professo_Address_id_8a13c622_fk_informati" FOREIGN KEY ("Address_id")
    REFERENCES public.information_address (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_professor_Address_id_8a13c622"
    ON public.information_professor("Address_id");


ALTER TABLE IF EXISTS public.information_professor
    ADD CONSTRAINT information_professo_department_id_939e95a5_fk_informati FOREIGN KEY (department_id)
    REFERENCES public.information_department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS information_professor_department_id_939e95a5
    ON public.information_professor(department_id);


ALTER TABLE IF EXISTS public.information_professor
    ADD CONSTRAINT information_professo_subject_id_56697c81_fk_informati FOREIGN KEY (subject_id)
    REFERENCES public.information_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS information_professor_subject_id_56697c81
    ON public.information_professor(subject_id);


ALTER TABLE IF EXISTS public.information_professordepartment
    ADD CONSTRAINT "information_professo_Department_ID_id_e9f11af3_fk_informati" FOREIGN KEY ("Department_ID_id")
    REFERENCES public.information_department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_professordepartment_Department_ID_id_e9f11af3"
    ON public.information_professordepartment("Department_ID_id");


ALTER TABLE IF EXISTS public.information_professordepartment
    ADD CONSTRAINT "information_professo_professor_ID_id_2bb1132c_fk_informati" FOREIGN KEY ("professor_ID_id")
    REFERENCES public.information_professor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_professordepartment_professor_ID_id_2bb1132c"
    ON public.information_professordepartment("professor_ID_id");


ALTER TABLE IF EXISTS public.information_professorsubject
    ADD CONSTRAINT "information_professo_TA_ID_id_2b726b61_fk_informati" FOREIGN KEY ("TA_ID_id")
    REFERENCES public.information_teachingassistant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_professorsubject_TA_ID_id_2b726b61"
    ON public.information_professorsubject("TA_ID_id");


ALTER TABLE IF EXISTS public.information_professorsubject
    ADD CONSTRAINT "information_professo_professor_ID_id_be66f438_fk_informati" FOREIGN KEY ("professor_ID_id")
    REFERENCES public.information_professor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_professorsubject_professor_ID_id_be66f438"
    ON public.information_professorsubject("professor_ID_id");


ALTER TABLE IF EXISTS public.information_professorsubject
    ADD CONSTRAINT "information_professo_subject_ID_id_6be1d30d_fk_informati" FOREIGN KEY ("subject_ID_id")
    REFERENCES public.information_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_professorsubject_subject_ID_id_6be1d30d"
    ON public.information_professorsubject("subject_ID_id");


ALTER TABLE IF EXISTS public.information_student
    ADD CONSTRAINT "information_student_Address_id_cf070dc8_fk_informati" FOREIGN KEY ("Address_id")
    REFERENCES public.information_address (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_student_Address_id_cf070dc8"
    ON public.information_student("Address_id");


ALTER TABLE IF EXISTS public.information_student
    ADD CONSTRAINT information_student_department_id_db620181_fk_informati FOREIGN KEY (department_id)
    REFERENCES public.information_department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS information_student_department_id_db620181
    ON public.information_student(department_id);


ALTER TABLE IF EXISTS public.information_student
    ADD CONSTRAINT information_student_subject_id_fdb8d1e7_fk_informati FOREIGN KEY (subject_id)
    REFERENCES public.information_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS information_student_subject_id_fdb8d1e7
    ON public.information_student(subject_id);


ALTER TABLE IF EXISTS public.information_student_ta
    ADD CONSTRAINT "information_student__TA_ID_id_8faf308a_fk_informati" FOREIGN KEY ("TA_ID_id")
    REFERENCES public.information_teachingassistant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_student_ta_TA_ID_id_8faf308a"
    ON public.information_student_ta("TA_ID_id");


ALTER TABLE IF EXISTS public.information_student_ta
    ADD CONSTRAINT "information_student__student_ID_id_8ef80b9d_fk_informati" FOREIGN KEY ("student_ID_id")
    REFERENCES public.information_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_student_ta_student_ID_id_8ef80b9d"
    ON public.information_student_ta("student_ID_id");


ALTER TABLE IF EXISTS public.information_student_ta
    ADD CONSTRAINT "information_student__subject_ID_id_18b681af_fk_informati" FOREIGN KEY ("subject_ID_id")
    REFERENCES public.information_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_student_ta_subject_ID_id_18b681af"
    ON public.information_student_ta("subject_ID_id");


ALTER TABLE IF EXISTS public.information_studentprofessor
    ADD CONSTRAINT "information_studentp_professor_ID_id_18d2cff8_fk_informati" FOREIGN KEY ("professor_ID_id")
    REFERENCES public.information_professor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_studentprofessor_professor_ID_id_18d2cff8"
    ON public.information_studentprofessor("professor_ID_id");


ALTER TABLE IF EXISTS public.information_studentprofessor
    ADD CONSTRAINT "information_studentp_student_ID_id_840fb34f_fk_informati" FOREIGN KEY ("student_ID_id")
    REFERENCES public.information_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_studentprofessor_student_ID_id_840fb34f"
    ON public.information_studentprofessor("student_ID_id");


ALTER TABLE IF EXISTS public.information_studentprofessor
    ADD CONSTRAINT "information_studentp_subject_ID_id_2fb3d81a_fk_informati" FOREIGN KEY ("subject_ID_id")
    REFERENCES public.information_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_studentprofessor_subject_ID_id_2fb3d81a"
    ON public.information_studentprofessor("subject_ID_id");


ALTER TABLE IF EXISTS public.information_studentsection
    ADD CONSTRAINT "information_students_section_ID_id_a9c6a402_fk_informati" FOREIGN KEY ("section_ID_id")
    REFERENCES public.information_section (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_studentsection_section_ID_id_a9c6a402"
    ON public.information_studentsection("section_ID_id");


ALTER TABLE IF EXISTS public.information_studentsection
    ADD CONSTRAINT "information_students_student_ID_id_3e43f0d7_fk_informati" FOREIGN KEY ("student_ID_id")
    REFERENCES public.information_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_studentsection_student_ID_id_3e43f0d7"
    ON public.information_studentsection("student_ID_id");


ALTER TABLE IF EXISTS public.information_studentsubject
    ADD CONSTRAINT "information_students_TA_ID_id_847e943a_fk_informati" FOREIGN KEY ("TA_ID_id")
    REFERENCES public.information_teachingassistant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_studentsubject_TA_ID_id_847e943a"
    ON public.information_studentsubject("TA_ID_id");


ALTER TABLE IF EXISTS public.information_studentsubject
    ADD CONSTRAINT "information_students_professor_ID_id_a50964a0_fk_informati" FOREIGN KEY ("professor_ID_id")
    REFERENCES public.information_professor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_studentsubject_professor_ID_id_a50964a0"
    ON public.information_studentsubject("professor_ID_id");


ALTER TABLE IF EXISTS public.information_studentsubject
    ADD CONSTRAINT "information_students_student_ID_id_d95cc1c3_fk_informati" FOREIGN KEY ("student_ID_id")
    REFERENCES public.information_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_studentsubject_student_ID_id_d95cc1c3"
    ON public.information_studentsubject("student_ID_id");


ALTER TABLE IF EXISTS public.information_studentsubject
    ADD CONSTRAINT "information_students_subject_ID_id_04fee8e5_fk_informati" FOREIGN KEY ("subject_ID_id")
    REFERENCES public.information_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_studentsubject_subject_ID_id_04fee8e5"
    ON public.information_studentsubject("subject_ID_id");


ALTER TABLE IF EXISTS public.information_ta_department
    ADD CONSTRAINT "information_ta_depar_Department_ID_id_02168024_fk_informati" FOREIGN KEY ("Department_ID_id")
    REFERENCES public.information_department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_ta_department_Department_ID_id_02168024"
    ON public.information_ta_department("Department_ID_id");


ALTER TABLE IF EXISTS public.information_ta_department
    ADD CONSTRAINT "information_ta_depar_TA_ID_id_55056c28_fk_informati" FOREIGN KEY ("TA_ID_id")
    REFERENCES public.information_professor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_ta_department_TA_ID_id_55056c28"
    ON public.information_ta_department("TA_ID_id");


ALTER TABLE IF EXISTS public.information_ta_section
    ADD CONSTRAINT "information_ta_secti_TA_ID_id_c5e22b5c_fk_informati" FOREIGN KEY ("TA_ID_id")
    REFERENCES public.information_teachingassistant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_ta_section_TA_ID_id_c5e22b5c"
    ON public.information_ta_section("TA_ID_id");


ALTER TABLE IF EXISTS public.information_ta_section
    ADD CONSTRAINT "information_ta_secti_section_ID_id_164d95f7_fk_informati" FOREIGN KEY ("section_ID_id")
    REFERENCES public.information_section (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_ta_section_section_ID_id_164d95f7"
    ON public.information_ta_section("section_ID_id");


ALTER TABLE IF EXISTS public.information_ta_subject
    ADD CONSTRAINT "information_ta_subje_TA_ID_id_deac3c5d_fk_informati" FOREIGN KEY ("TA_ID_id")
    REFERENCES public.information_teachingassistant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_ta_subject_TA_ID_id_deac3c5d"
    ON public.information_ta_subject("TA_ID_id");


ALTER TABLE IF EXISTS public.information_ta_subject
    ADD CONSTRAINT "information_ta_subje_professor_ID_id_cb41b8c3_fk_informati" FOREIGN KEY ("professor_ID_id")
    REFERENCES public.information_professor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_ta_subject_professor_ID_id_cb41b8c3"
    ON public.information_ta_subject("professor_ID_id");


ALTER TABLE IF EXISTS public.information_ta_subject
    ADD CONSTRAINT "information_ta_subje_subject_ID_id_4ff3d53c_fk_informati" FOREIGN KEY ("subject_ID_id")
    REFERENCES public.information_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_ta_subject_subject_ID_id_4ff3d53c"
    ON public.information_ta_subject("subject_ID_id");


ALTER TABLE IF EXISTS public.information_teachingassistant
    ADD CONSTRAINT "information_teaching_Address_id_6ec63c1b_fk_informati" FOREIGN KEY ("Address_id")
    REFERENCES public.information_address (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "information_teachingassistant_Address_id_6ec63c1b"
    ON public.information_teachingassistant("Address_id");


ALTER TABLE IF EXISTS public.information_teachingassistant
    ADD CONSTRAINT information_teaching_department_id_56c3cb4c_fk_informati FOREIGN KEY (department_id)
    REFERENCES public.information_department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS information_teachingassistant_department_id_56c3cb4c_uniq
    ON public.information_teachingassistant(department_id);


ALTER TABLE IF EXISTS public.information_teachingassistant
    ADD CONSTRAINT information_teaching_subject_id_0e27c5f3_fk_informati FOREIGN KEY (subject_id)
    REFERENCES public.information_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS information_teachingassistant_subject_id_0e27c5f3_uniq
    ON public.information_teachingassistant(subject_id);

END;
